# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: rchoquer <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2016/11/04 05:16:00 by rchoquer          #+#    #+#              #
#    Updated: 2016/11/04 07:20:31 by rchoquer         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = ft_display_file
SRC = ft_display_file.c

all:$(NAME)

$(NAME):
	@gcc -Werror -Wextra -Wall -o $(NAME) $(SRC)

clean:
	@rm -f

fclean: clean
	@rm -f ft_display_file
